export const SEARCH_FOCUS = 'header/search_focus'
export const FETCH_SEARCH_LIST = 'header/fetch_search_list'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'
export const CHANGE_PAGE = 'header/change_page'